project:
  type: website
  output-dir: ../docs

execute:
  # freeze: auto
  echo: false
  warning: false
  
website:
  title: "Tree Rings"
  google-analytics: "G-LXSX23EQ95"
  reader-mode: false
  page-footer: Â© Beep Boop Stats
  # top nav
  navbar:
    pinned: true
    logo: ../assets/img/favicon.png
    search: true
    left:
      - text: "Contact"
        file: contact/index.qmd
    css: ../assets/css/styles.scss

format:
  html:
    theme: 
      light: 
        - pulse
        - ../assets/css/styles.scss
    fontsize: 1.1em
    page-layout: full
    toc: true
    toc-depth: 3
    toc-location: left
    toc-expand: 1
    embed-resources: true
    # new options
    toc_float: true
    code-overflow: wrap
    code-fold: true
    code-summary: "Show code"

format-links: []
